spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_publishing_house
    username: postgres
    password: PASSWORD
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          time_zone: UTC


server:
  port: 8081

application:
  authserver:
    port: 8080
    key-uri: http://localhost::getPort/jwks.json
    claims:
      role: scope
      expiry: exp